# Enhanced Parameter Detection Configuration
# This file maps column names to parameter patterns and synonyms

parameter_mapping:
  # Purchase Order View Column Mappings (ZC_PO_List)
  po_materials_parameters:
    PurchaseOrder:
      field_name: "PurchaseOrder"
      odata_field: "PurchaseOrder"
      synonyms: ["purchase order", "po number", "po", "purchase order number", "ebeln", "order number"]
      patterns: 
        - "purchase order (is|equals|=) {value}"
        - "po (number|=|equals|is) {value}"
        - "purchase order number {value}"
        - "ebeln {value}"
      data_type: "string"
      example_values: ["4500000001", "4500000002"]
    
    Item:
      field_name: "Item"
      odata_field: "Item" 
      synonyms: ["item", "item number", "line item", "po item", "ebelp", "line"]
      patterns:
        - "item (number|is|equals|=) {value}"
        - "line item {value}"
        - "po item {value}"
        - "ebelp {value}"
      data_type: "string"
      example_values: ["10", "20", "30"]
    
    VendorId:
      field_name: "VendorId"
      odata_field: "VendorId"
      synonyms: ["vendor id", "vendor", "lifnr", "supplier id", "supplier"]
      patterns:
        - "vendor (id|=|is|equals) {value}"
        - "lifnr {value}"
        - "supplier (id|=|is|equals) {value}"
        - "vendor {value}"
      data_type: "string"
      example_values: ["100001", "100002", "200001"]
    
    VendorName:
      field_name: "VendorName"
      odata_field: "VendorName"
      synonyms: ["vendor name", "supplier name", "name1", "vendor company"]
      patterns:
        - "vendor name (is|equals|=) {value}"
        - "supplier name {value}"
        - "name1 {value}"
        - "vendor company {value}"
      data_type: "string"
      example_values: ["ABC Corp", "XYZ Ltd", "Tech Solutions"]
    
    Material:
      field_name: "Material"
      odata_field: "Material"
      synonyms: ["material", "material number", "matnr", "part number", "product"]
      patterns:
        - "material (number|is|equals|=) {value}"
        - "matnr {value}"
        - "part number {value}"
        - "product {value}"
      data_type: "string"
      example_values: ["MAT001", "MAT002", "PART123"]
    
    Plant:
      field_name: "Plant"
      odata_field: "Plant"
      synonyms: ["plant", "plant code", "werks", "location", "site"]
      patterns:
        - "plant (code|is|equals|=) {value}"
        - "werks {value}"
        - "location {value}"
        - "site {value}"
      data_type: "string"
      example_values: ["1000", "2000", "3000"]
    
    OrderQty:
      field_name: "OrderQty"
      odata_field: "OrderQty"
      synonyms: ["order quantity", "quantity", "qty", "menge", "order qty"]
      patterns:
        - "order quantity (is|equals|=|>) {value}"
        - "quantity {value}"
        - "qty {value}"
        - "menge {value}"
      data_type: "decimal"
      example_values: ["100", "250.5", "1000"]
    
    NetPrice:
      field_name: "NetPrice"
      odata_field: "NetPrice"
      synonyms: ["net price", "price", "netpr", "cost", "rate"]
      patterns:
        - "net price (is|equals|=|>) {value}"
        - "price {value}"
        - "netpr {value}"
        - "cost {value}"
        - "rate {value}"
      data_type: "decimal"
      example_values: ["10.50", "25.00", "100.75"]
    
    Currency:
      field_name: "Currency"
      odata_field: "Currency"
      synonyms: ["currency", "currency code", "waers"]
      patterns:
        - "currency (code|is|equals|=) {value}"
        - "waers {value}"
        - "currency {value}"
      data_type: "string"
      example_values: ["USD", "EUR", "INR"]
    
    Salary:
      field_name: "Salary"
      odata_field: "Salary"
      synonyms: ["salary", "pay", "compensation", "wage", "income", "remuneration"]
      patterns:
        - "salary (is|equals|=|>|<) {value}"
        - "pay (is|equals|=|>|<) {value}"
        - "compensation {value}"
        - "wage {value}"
        - "income {value}"
        - "remuneration {value}"
      data_type: "decimal"
      example_values: ["50000", "75000.50", "100000"]
    
    Department:
      field_name: "Department"
      odata_field: "Department"
      synonyms: ["department", "dept", "division", "unit", "section", "team", "org unit"]
      patterns:
        - "department (is|equals|=) {value}"
        - "dept (is|equals|=) {value}"
        - "division {value}"
        - "unit {value}"
        - "section {value}"
        - "team {value}"
        - "org unit {value}"
      data_type: "string"
      example_values: ["IT", "HR", "Finance", "Sales", "Marketing", "Operations"]

# Common parameter patterns for all intents
common_patterns:
  comparison_operators:
    equals: ["is", "equals", "=", "equal to"]
    greater_than: ["greater than", ">", "more than", "above"]
    less_than: ["less than", "<", "below", "under"]
    contains: ["contains", "includes", "has", "like"]
    not_equals: ["not equal to", "!=", "not", "different from"]
  
  value_extraction:
    quoted_strings: '"([^"]+)"'
    single_quoted: "'([^']+)'"
    alphanumeric: "([A-Za-z0-9]+)"
    numbers: "([0-9]+\\.?[0-9]*)"
    dates: "(\\d{4}-\\d{2}-\\d{2})"
